### ISSUE TITLE
Query regarding Column values

### ISSUE THREAD

**Issue by AumkarG** [geniusai-research/interns_task#6]
Can you please tell me what vas_counts, business type and active ads means?
Also the target variable is whether the customer stays or leaves, so does 0 mean that the customer stays, or does 1 mean that the customer stays?
Also, the maximum number of days when the user made a repurchase... what does that exactly mean? Maximum gap between two purchases?

**Comment by Manav-03** [comment]
@AumkarG I have similar doubts about the data.

**Comment by AumkarG** [comment]
Yes, it is difficult to derive good insights from the EDA without more information on the variables.

**Comment by goodrahstar** [comment]
Hi,

target:=0 is Customer leaves
target:=1 is Customer stays

Yes, the maximum number of days indicates a Maximum gap between subsequent purchases.

Refer `data_description.md` for the data description. 

-Thanks

**Comment by Manav-03** [comment]
@goodrahstar Thank you for clarifying. :)

**Comment by AumkarG** [comment]
@goodrahstar Thank you :)
