### ISSUE TITLE
PR issue

### ISSUE THREAD

**Issue by Thanushri16** [geniusai-research/interns_task#7]
I have an issue in creating a pull request after forking the private repository. It says that there is nothing to commit which means the files are similar. 
![Capture](https://user-images.githubusercontent.com/56839189/97101891-069a2380-16c7-11eb-8cf6-5835c317071b.JPG)

**Comment by Nikhil1O1** [comment]
Are you certain that you made your changes in the main branch of your fork or some other branch?

**Comment by Thanushri16** [comment]
Yes, I have made the changes. Is it possible for me to mail you the python file? Thanks Thanushri Sent from Mail for Windows 10 From: Nikhil ChoudharySent: 27 October 2020 08:27To: geniusai-research/interns_taskCc: Thanushri16; AuthorSubject: Re: [geniusai-research/interns_task] PR issue (#7) Are you certain that you made your changes in the main branch of your fork or some other branch?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Nikhil1O1** [comment]
Actually do one thing
Mail me the python file and i will upload it on your behalf?.
Will this do?

**Comment by Thanushri16** [comment]
Sure that will be fine! I will mail it within a hour

**Comment by Thanushri16** [comment]
I have attached the python file in this mail. You can feel free to contact for further clarifications. Thank you for addressing this issue.  Thank youThanushri R Sent from Mail for Windows 10 From: Nikhil ChoudharySent: 27 October 2020 23:00To: geniusai-research/interns_taskCc: Thanushri16; AuthorSubject: Re: [geniusai-research/interns_task] PR issue (#7) Actually do one thingMail me the python file and i will upload it on your behalf?.Will this do?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
